# Change these first
owner: Kuantaz # Your GitHub organization or username, where this repository lives
repo: rps-check # The name of this repository

sites:
  - name: RPS
    url: https://www.reddeproteccion.cl
    
assigness:
  - JhonFuenzalida
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /rps-check
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**RPS** uptime monitor and status page"
  navbar:
    - title: Status
      href: /


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
